apiVersion: clm.cloudnativeapp.io/v1beta1
kind: Source
metadata:
  name: helm-source
spec:
  type: helm
  implement:
    helm:
      wait: true
      timeout: 120
      repositories:
        - name: bitnami
          url: https://charts.bitnami.com/bitnami
        - name: nginx-stable
          url: https://helm.nginx.com/stable